EMAIL:
  title: 测试报告
  message: 测试报告见附件！
  password: zxg680210
  receiver: 342509492@qq.com
  sender: zxg_com@163.com
  server: smtp.163.com

DB_huizhen:
  host: wwwhuizhen.mysql.rds.aliyuncs.com
  user: ceshi
  passwd: (Djf9#8d
  port: 3317
  db: tocure_platform

DB_allin:
  host:
  user: dev
  passwd:
  port:
  db: allin_platform

log:
  backup: 5
  console_level: WARNING
  file_level: INFO
  file_name: Output
  pattern: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'


EVIORMENT:
  port: 4720
  bp: 4900
  threshold_shape : 0.8
  threshold_histogram : 0.4

WECHART: #企业号通知
  corpid: wwcf07c49f733cad2f  #appid
  corpsecret: PfiBVYx_NC1zHV5S8TBFZGQnRJ8Dai1T9Dga9jGJ0pk  #秘钥
  agentid: 1000002      #应用id


ServerInfo:
  ip: 47.94.81.110
  port: 8085
  name:
  password: